USE feltrinelli;

CREATE TABLE if NOT EXISTS REGISTRAZIONI (
   id INT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(255),
   SURNAME VARCHAR(255),
   USERNAME VARCHAR(255) UNIQUE,
   EMAIL VARCHAR(255) UNIQUE,
   PASSWORD VARCHAR(255)
);

CREATE TABLE if NOT EXISTS UTENTI (
   id INT AUTO_INCREMENT PRIMARY KEY,
   USERNAME VARCHAR(255) UNIQUE,
   PASSWORD VARCHAR(255),
   FOREIGN KEY (USERNAME) REFERENCES REGISTRAZIONI(USERNAME)
);

CREATE TABLE if NOT EXISTS PREFERITI (
	USERNAME VARCHAR(255),
	TITOLO VARCHAR(255),
	COPERTINA VARCHAR(255),
	AUTORE VARCHAR(255),
	PREZZO INTEGER,
	TIPOLOGIA VARCHAR(50),
	UNIQUE (USERNAME, TITOLO, AUTORE)
);
	
CREATE TABLE IF NOT EXISTS CARRELLO(
	USERNAME VARCHAR(255),
	TITOLO VARCHAR(255),
	COPERTINA VARCHAR(255),
	AUTORE VARCHAR(255),
	PREZZO INTEGER,
	TIPOLOGIA VARCHAR(50),
	QUANTITY INT DEFAULT 1 /*nel carrello non mettiamo le unique perché può aggiungere più copie dello stesso prodotto*/
);

CREATE TABLE IF NOT EXISTS LIKES(
	USERNAME VARCHAR(255),
	TITOLO VARCHAR(255),
	COPERTINA VARCHAR(255),
	AUTORE VARCHAR(255),
	TIPOLOGIA VARCHAR(50),
	UNIQUE (USERNAME, TITOLO, AUTORE, TIPOLOGIA) /*così l'utente può mettere like una sola volta a quel prodotto*/
);

CREATE TABLE IF NOT EXISTS TOKENS(
	USERNAME VARCHAR(255),
	TOKEN VARCHAR(64),
	SCADENZA DATE
);

CREATE TABLE IF NOT EXISTS PRODOTTI(
	ID INT AUTO_INCREMENT PRIMARY KEY,
   TITOLO VARCHAR(255),
   COPERTINA VARCHAR(255),
   AUTORE VARCHAR(255),
   PREZZO INT,
   TIPOLOGIA VARCHAR(50),
   LINK VARCHAR(255),
   UNIQUE(TITOLO, AUTORE, TIPOLOGIA)
);